import Head from 'next/head';
import Image from 'next/image';
import { HeroSection } from '../collections';
import { Button } from '../components';

export default function Home() {
  return (
    <>
      <Head>
        <title>ZontaCoin</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='container mx-auto'>
        <section className='my-16'>
          <HeroSection />
        </section>
      </main>
    </>
  );
}
