import Head from 'next/head';
import Image from 'next/image';
import {
  AdditionalFeatures,
  EcoFriendly,
  Features,
  HeroSection,
  OurGoals,
  OurPartners,
  OurRoadmap,
  TradingModel,
  ZontaIntro,
} from '../collections';
import { Navbar } from '../components/Navbar/Navbar';

export default function Home() {
  return (
    <>
      <Head>
        <title>ZontaCoin</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* <Navbar /> */}
      <main>
        <div className='container mx-auto'>
          <section>
            <HeroSection />
          </section>
          <section>
            <OurPartners className='my-10' />
          </section>
          <section className='my-20'>
            <ZontaIntro />
          </section>
          <section className='my-20'>
            <Features />
          </section>
          <section className='my-20'>
            <TradingModel />
          </section>
        </div>

        <section className='my-20'>
          <EcoFriendly />
        </section>

        <div className='container mx-auto'>
          <section>
            <AdditionalFeatures />
          </section>

          <section className='my-24'>
            <OurGoals />
          </section>

          <section className='my-24'>
            <OurRoadmap />
          </section>
        </div>
      </main>
    </>
  );
}
